// Code generated by protoc-gen-go.
// source: coffeelog.proto
// DO NOT EDIT!

/*
Package coffeelog is a generated protocol buffer package.

It is generated from these files:
	coffeelog.proto

It has these top-level messages:
	User
	GoogleUser
	HelloMessage
*/
package coffeelog

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type User struct {
	ID          string `protobuf:"bytes,1,opt,name=ID" json:"ID,omitempty"`
	DisplayName string `protobuf:"bytes,2,opt,name=DisplayName" json:"DisplayName,omitempty"`
	Picture     string `protobuf:"bytes,3,opt,name=Picture" json:"Picture,omitempty"`
}

func (m *User) Reset()                    { *m = User{} }
func (m *User) String() string            { return proto.CompactTextString(m) }
func (*User) ProtoMessage()               {}
func (*User) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *User) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *User) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

func (m *User) GetPicture() string {
	if m != nil {
		return m.Picture
	}
	return ""
}

type GoogleUser struct {
	ID          string `protobuf:"bytes,1,opt,name=ID" json:"ID,omitempty"`
	DisplayName string `protobuf:"bytes,2,opt,name=DisplayName" json:"DisplayName,omitempty"`
	PictureURL  string `protobuf:"bytes,3,opt,name=PictureURL" json:"PictureURL,omitempty"`
	Email       string `protobuf:"bytes,4,opt,name=Email" json:"Email,omitempty"`
}

func (m *GoogleUser) Reset()                    { *m = GoogleUser{} }
func (m *GoogleUser) String() string            { return proto.CompactTextString(m) }
func (*GoogleUser) ProtoMessage()               {}
func (*GoogleUser) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *GoogleUser) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *GoogleUser) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

func (m *GoogleUser) GetPictureURL() string {
	if m != nil {
		return m.PictureURL
	}
	return ""
}

func (m *GoogleUser) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type HelloMessage struct {
	Message string `protobuf:"bytes,1,opt,name=Message" json:"Message,omitempty"`
}

func (m *HelloMessage) Reset()                    { *m = HelloMessage{} }
func (m *HelloMessage) String() string            { return proto.CompactTextString(m) }
func (*HelloMessage) ProtoMessage()               {}
func (*HelloMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *HelloMessage) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*User)(nil), "User")
	proto.RegisterType((*GoogleUser)(nil), "GoogleUser")
	proto.RegisterType((*HelloMessage)(nil), "HelloMessage")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for UserDirectory service

type UserDirectoryClient interface {
	AuthorizeGoogle(ctx context.Context, in *GoogleUser, opts ...grpc.CallOption) (*User, error)
}

type userDirectoryClient struct {
	cc *grpc.ClientConn
}

func NewUserDirectoryClient(cc *grpc.ClientConn) UserDirectoryClient {
	return &userDirectoryClient{cc}
}

func (c *userDirectoryClient) AuthorizeGoogle(ctx context.Context, in *GoogleUser, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := grpc.Invoke(ctx, "/UserDirectory/AuthorizeGoogle", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for UserDirectory service

type UserDirectoryServer interface {
	AuthorizeGoogle(context.Context, *GoogleUser) (*User, error)
}

func RegisterUserDirectoryServer(s *grpc.Server, srv UserDirectoryServer) {
	s.RegisterService(&_UserDirectory_serviceDesc, srv)
}

func _UserDirectory_AuthorizeGoogle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GoogleUser)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserDirectoryServer).AuthorizeGoogle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/UserDirectory/AuthorizeGoogle",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserDirectoryServer).AuthorizeGoogle(ctx, req.(*GoogleUser))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserDirectory_serviceDesc = grpc.ServiceDesc{
	ServiceName: "UserDirectory",
	HandlerType: (*UserDirectoryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AuthorizeGoogle",
			Handler:    _UserDirectory_AuthorizeGoogle_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "coffeelog.proto",
}

// Client API for Hello service

type HelloClient interface {
	Say(ctx context.Context, in *HelloMessage, opts ...grpc.CallOption) (*HelloMessage, error)
}

type helloClient struct {
	cc *grpc.ClientConn
}

func NewHelloClient(cc *grpc.ClientConn) HelloClient {
	return &helloClient{cc}
}

func (c *helloClient) Say(ctx context.Context, in *HelloMessage, opts ...grpc.CallOption) (*HelloMessage, error) {
	out := new(HelloMessage)
	err := grpc.Invoke(ctx, "/Hello/Say", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Hello service

type HelloServer interface {
	Say(context.Context, *HelloMessage) (*HelloMessage, error)
}

func RegisterHelloServer(s *grpc.Server, srv HelloServer) {
	s.RegisterService(&_Hello_serviceDesc, srv)
}

func _Hello_Say_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HelloServer).Say(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Hello/Say",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HelloServer).Say(ctx, req.(*HelloMessage))
	}
	return interceptor(ctx, in, info, handler)
}

var _Hello_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Hello",
	HandlerType: (*HelloServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Say",
			Handler:    _Hello_Say_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "coffeelog.proto",
}

func init() { proto.RegisterFile("coffeelog.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 235 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x9c, 0x90, 0x41, 0x4b, 0x03, 0x31,
	0x14, 0x84, 0xdb, 0x6d, 0x57, 0xf1, 0xd5, 0x5a, 0x78, 0x78, 0x08, 0x3d, 0x48, 0x09, 0x88, 0x3d,
	0xe5, 0x50, 0x2f, 0x5e, 0x85, 0x88, 0x16, 0x54, 0x64, 0xa5, 0x3f, 0x20, 0x2e, 0xaf, 0x6b, 0x20,
	0xe5, 0x95, 0x24, 0x3d, 0xac, 0xbf, 0x5e, 0x9a, 0xa6, 0xb8, 0x5e, 0x7b, 0x4a, 0xbe, 0x19, 0x98,
	0x99, 0x04, 0x26, 0x35, 0xaf, 0xd7, 0x44, 0x8e, 0x1b, 0xb5, 0xf5, 0x1c, 0x59, 0x56, 0x30, 0x5c,
	0x05, 0xf2, 0x78, 0x05, 0xc5, 0x52, 0x8b, 0xfe, 0xac, 0x3f, 0xbf, 0xa8, 0x8a, 0xa5, 0xc6, 0x19,
	0x8c, 0xb4, 0x0d, 0x5b, 0x67, 0xda, 0x77, 0xb3, 0x21, 0x51, 0x24, 0xa3, 0x2b, 0xa1, 0x80, 0xf3,
	0x0f, 0x5b, 0xc7, 0x9d, 0x27, 0x31, 0x48, 0xee, 0x11, 0x65, 0x04, 0x78, 0x66, 0x6e, 0x1c, 0x9d,
	0x98, 0x7c, 0x03, 0x90, 0xa3, 0x56, 0xd5, 0x6b, 0x0e, 0xef, 0x28, 0x78, 0x0d, 0xe5, 0xd3, 0xc6,
	0x58, 0x27, 0x86, 0xc9, 0x3a, 0x80, 0x9c, 0xc3, 0xe5, 0x0b, 0x39, 0xc7, 0x6f, 0x14, 0x82, 0x69,
	0xd2, 0xbe, 0x7c, 0xcd, 0xe5, 0x47, 0x5c, 0x3c, 0xc0, 0x78, 0xbf, 0x4c, 0x5b, 0x4f, 0x75, 0x64,
	0xdf, 0xe2, 0x1d, 0x4c, 0x1e, 0x77, 0xf1, 0x9b, 0xbd, 0xfd, 0xa1, 0xc3, 0x72, 0x1c, 0xa9, 0xbf,
	0x27, 0x4c, 0x4b, 0xb5, 0x3f, 0x64, 0x6f, 0xa1, 0xa0, 0x4c, 0x1d, 0x78, 0x0b, 0x83, 0x4f, 0xd3,
	0xe2, 0x58, 0x75, 0x2b, 0xa7, 0xff, 0x51, 0xf6, 0xbe, 0xce, 0xd2, 0x27, 0xdf, 0xff, 0x06, 0x00,
	0x00, 0xff, 0xff, 0x8e, 0x25, 0x1e, 0x27, 0x77, 0x01, 0x00, 0x00,
}
